// Copyright 2024 Heathen Engineering
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if UNITY_EDITOR && !DISABLESTEAMWORKS && STEAM_INSTALLED
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Heathen.SteamworksIntegration
{
    /// <summary>
    /// Generates <c>SteamTools.Game.cs</c> — the Foundation-compatible runtime wrapper that
    /// wires up your App IDs, Achievements, Stats, and Leaderboards in a single generated class.
    /// <para>
    /// Foundation produces a simpler wrapper than Toolkit:
    /// no DLC, no Server Config, no Input actions.
    /// <see cref="SteamTools.Interface.RaiseOnReady"/> receives only the board map.
    /// </para>
    /// </summary>
    public static class SteamToolsCodeGenerator
    {
        private const string ScriptName        = "SteamTools.Game.cs";
        private const string DefaultOutputPath = "Assets/Scripts/Generated/SteamTools.Game.cs";

        // Marker used to identify an existing generated file so we don't
        // overwrite a user-created file that happens to share the name.
        private const string GeneratedMarker = "// Auto-generated by SteamToolsCodeGenerator";

        // ---------------------------------------------------------------
        // Public entry point
        // ---------------------------------------------------------------

        /// <summary>
        /// Re-generates <c>SteamTools.Game.cs</c> from <paramref name="settings"/>.
        /// Writes over the existing file if one is found; otherwise creates it at
        /// <c>Assets/SteamTools.Game.cs</c>.
        /// </summary>
        public static void Generate(SteamToolsSettings settings)
        {
            if (settings == null) throw new ArgumentNullException(nameof(settings));

            settings.CollectUniqueData();

            var path = FindExistingScript() ?? DefaultOutputPath;
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? string.Empty);

            File.WriteAllText(path, BuildCode(settings));
            AssetDatabase.Refresh();

            settings.LastGenerated = DateTime.Now;
            EditorUtility.SetDirty(settings);
            AssetDatabase.SaveAssets();

            Debug.Log($"[SteamToolsCodeGenerator] Generated {ScriptName} at {path}");
        }

        // ---------------------------------------------------------------
        // Internal helpers
        // ---------------------------------------------------------------

        private static string FindExistingScript()
        {
            var guids = AssetDatabase.FindAssets($"SteamTools.Game t:Script");
            return (from guid in guids
                    select AssetDatabase.GUIDToAssetPath(guid) into p
                    let text = File.ReadAllText(p)
                    where text.Contains(GeneratedMarker)
                    select p).FirstOrDefault();
        }

        private static string BuildCode(SteamToolsSettings s)
        {
            var sb = new StringBuilder();

            // ---- File header ----
            sb.AppendLine("// Auto-generated by SteamToolsCodeGenerator — do not edit by hand.");
            sb.AppendLine("// Re-generate via Project Settings > Steamworks > Generate Code.");
            sb.AppendLine();
            sb.AppendLine("#if !DISABLESTEAMWORKS");
            sb.AppendLine("using Heathen.SteamworksIntegration;");
            sb.AppendLine("using Heathen.SteamworksIntegration.API;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace SteamTools");
            sb.AppendLine("{");
            sb.AppendLine("    public static class Game");
            sb.AppendLine("    {");
            sb.AppendLine();

            AppendAppId(sb, s);
            AppendAchievements(sb, s);
            AppendStats(sb, s);
            AppendLeaderboards(sb, s);
            AppendInitialise(sb, s);
            AppendHandleInitialised(sb, s);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            return sb.ToString();
        }

        // ----------------------------------------------------------------
        // AppId — per-app #if chain so the right ID is compiled in.
        // ----------------------------------------------------------------

        private static void AppendAppId(StringBuilder sb, SteamToolsSettings s)
        {
            for (var i = 0; i < s.appIds.Count; i++)
            {
                var id = s.appIds[i];
                sb.AppendLine(i == 0 ? $"#if APP{id}" : $"#elif APP{id}");
                sb.AppendLine($"        public const uint AppId = {id};");
            }
            sb.AppendLine("#else");
            sb.AppendLine("        public const uint AppId = 0;");
            sb.AppendLine("#endif");
            sb.AppendLine();
        }

        // ----------------------------------------------------------------
        // Achievements static class
        // ----------------------------------------------------------------

        private static void AppendAchievements(StringBuilder sb, SteamToolsSettings s)
        {
            if (s.achievements.Count == 0) return;

            sb.AppendLine("        public static class Achievements");
            sb.AppendLine("        {");

            foreach (var name in s.achievements)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"            public static AchievementData {id} = \"{name}\";");
            }

            sb.AppendLine();
            sb.AppendLine("            public static Dictionary<string, AchievementData> GetMap() => new()");
            sb.AppendLine("            {");
            foreach (var name in s.achievements)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"                {{ \"{name}\", {id} }},");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------------------------------------------
        // Stats static class
        // ----------------------------------------------------------------

        private static void AppendStats(StringBuilder sb, SteamToolsSettings s)
        {
            if (s.stats.Count == 0) return;

            sb.AppendLine("        public static class Stats");
            sb.AppendLine("        {");

            foreach (var name in s.stats)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"            public static StatData {id} = \"{name}\";");
            }

            sb.AppendLine();
            sb.AppendLine("            public static Dictionary<string, StatData> GetMap() => new()");
            sb.AppendLine("            {");
            foreach (var name in s.stats)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"                {{ \"{name}\", {id} }},");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------------------------------------------
        // Leaderboards static class
        // ----------------------------------------------------------------

        private static void AppendLeaderboards(StringBuilder sb, SteamToolsSettings s)
        {
            if (s.leaderboards.Count == 0) return;

            sb.AppendLine("        public static class Leaderboards");
            sb.AppendLine("        {");

            foreach (var name in s.leaderboards)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"            public static LeaderboardData {id};");
            }

            sb.AppendLine();
            sb.AppendLine("            public static Dictionary<string, LeaderboardData> GetMap() => new()");
            sb.AppendLine("            {");
            foreach (var name in s.leaderboards)
            {
                var id = SteamToolsSettings.MakeValidIdentifier(name);
                sb.AppendLine($"                {{ \"{name}\", {id} }},");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------------------------------------------
        // Initialise()
        // ----------------------------------------------------------------

        private static void AppendInitialise(StringBuilder sb, SteamToolsSettings s)
        {
            sb.AppendLine("        private static bool _initialised;");
            sb.AppendLine();
            sb.AppendLine("        public static void Initialise()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_initialised) return;");
            sb.AppendLine("            _initialised = true;");
            sb.AppendLine();
            sb.AppendLine("            Interface.Initialise();");
            sb.AppendLine();
            sb.AppendLine("            Debug.Log($\"[SteamTools] Initialising for app {AppId}\");");
            sb.AppendLine("            SteamTools.Events.OnSteamInitialised += HandleInitialised;");
            sb.AppendLine("            App.Client.Initialise(AppId);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------------------------------------------
        // HandleInitialised()  — resolves leaderboards, then RaiseOnReady
        // ----------------------------------------------------------------

        private static void AppendHandleInitialised(StringBuilder sb, SteamToolsSettings s)
        {
            sb.AppendLine("        private static void HandleInitialised()");
            sb.AppendLine("        {");

            if (s.leaderboards.Count == 0)
            {
                // No leaderboards — just raise ready immediately.
                sb.AppendLine("            Interface.RaiseOnReady(new Dictionary<string, LeaderboardData>(), new Dictionary<string, InputActionSetData>(), new Dictionary<string, InputActionData>());");
            }
            else
            {
                // We need to fetch/create leaderboards per-app configuration then raise ready
                // once all boards have returned.  Each app's leaderboard list may differ,
                // so we emit an #if APP{id} chain matching the AppId section.
                bool anyApp = false;

                for (var i = 0; i < s.appIds.Count; i++)
                {
                    var appId      = s.appIds[i];
                    var appSettings = s.Get(appId);
                    if (appSettings == null || appSettings.leaderboards.Count == 0) continue;

                    sb.AppendLine(anyApp ? $"#elif APP{appId}" : $"#if APP{appId}");
                    anyApp = true;

                    var count = appSettings.leaderboards.Count;
                    sb.AppendLine($"            int boardCount = {count};");
                    sb.AppendLine( "            int returnedBoards = 0;");
                    sb.AppendLine();

                    foreach (var lb in appSettings.leaderboards)
                    {
                        var display = lb.displayType switch
                        {
                            Steamworks.ELeaderboardDisplayType.k_ELeaderboardDisplayTypeTimeSeconds =>
                                "Steamworks.ELeaderboardDisplayType.k_ELeaderboardDisplayTypeTimeSeconds",
                            Steamworks.ELeaderboardDisplayType.k_ELeaderboardDisplayTypeTimeMilliSeconds =>
                                "Steamworks.ELeaderboardDisplayType.k_ELeaderboardDisplayTypeTimeMilliSeconds",
                            _ => "Steamworks.ELeaderboardDisplayType.k_ELeaderboardDisplayTypeNumeric"
                        };

                        var sort = lb.sortMethod == Steamworks.ELeaderboardSortMethod.k_ELeaderboardSortMethodAscending
                            ? "Steamworks.ELeaderboardSortMethod.k_ELeaderboardSortMethodAscending"
                            : "Steamworks.ELeaderboardSortMethod.k_ELeaderboardSortMethodDescending";

                        var fieldId = SteamToolsSettings.MakeValidIdentifier(lb.name);

                        if (lb.createIfNotFound)
                        {
                            sb.AppendLine($"            LeaderboardData.GetOrCreate(\"{lb.name}\", {display}, {sort}, (result, ioError) =>");
                        }
                        else
                        {
                            sb.AppendLine($"            LeaderboardData.Get(\"{lb.name}\", (result, ioError) =>");
                        }

                        sb.AppendLine( "            {");
                        sb.AppendLine( "                if (!ioError)");
                        sb.AppendLine($"                    Leaderboards.{fieldId} = result;");
                        sb.AppendLine();
                        sb.AppendLine( "                returnedBoards++;");
                        sb.AppendLine( "                if (returnedBoards >= boardCount)");
                        sb.AppendLine( "                {");
                        sb.AppendLine( "                    Interface.RaiseOnReady(Leaderboards.GetMap(), new Dictionary<string, InputActionSetData>(), new Dictionary<string, InputActionData>());");
                        sb.AppendLine( "                }");
                        sb.AppendLine( "            });");
                        sb.AppendLine();
                    }
                }

                if (anyApp)
                {
                    // Fallback #else — no leaderboards for this app ID
                    sb.AppendLine("#else");
                    sb.AppendLine("            Interface.RaiseOnReady(new Dictionary<string, LeaderboardData>(), new Dictionary<string, InputActionSetData>(), new Dictionary<string, InputActionData>());");
                    sb.AppendLine("#endif");
                }
                else
                {
                    // Flat case: global leaderboard list, no per-app breakdown
                    sb.AppendLine($"            int boardCount = {s.leaderboards.Count};");
                    sb.AppendLine( "            int returnedBoards = 0;");
                    sb.AppendLine();

                    foreach (var name in s.leaderboards)
                    {
                        var fieldId = SteamToolsSettings.MakeValidIdentifier(name);

                        // Default: fetch only (use the global list which has no createIfNotFound info)
                        sb.AppendLine($"            LeaderboardData.Get(\"{name}\", (result, ioError) =>");
                        sb.AppendLine( "            {");
                        sb.AppendLine( "                if (!ioError)");
                        sb.AppendLine($"                    Leaderboards.{fieldId} = result;");
                        sb.AppendLine();
                        sb.AppendLine( "                returnedBoards++;");
                        sb.AppendLine( "                if (returnedBoards >= boardCount)");
                        sb.AppendLine( "                {");
                        sb.AppendLine( "                    Interface.RaiseOnReady(Leaderboards.GetMap(), new Dictionary<string, InputActionSetData>(), new Dictionary<string, InputActionData>());");
                        sb.AppendLine( "                }");
                        sb.AppendLine( "            });");
                        sb.AppendLine();
                    }
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
#endif
